---
- name: Import remi GPG key
  rpm_key:
    key: https://rpms.remirepo.net/enterprise/9/RPM-GPG-KEY-remi
    state: present

- name: Install remi repo
  dnf:
    name: https://rpms.remirepo.net/enterprise/remi-release-9.rpm
    state: latest

- name: Enable php remi repo
  shell: dnf module enable "{{ php_enablerepo | default(omit, true) }}" -y

- name: Install php
  dnf:
    enablerepo: "{{ php_enablerepo | default(omit, true) }}"
    install_weak_deps: false
    name: "{{ php_packages + php_packages_extra }}"
    state: latest



